### ISSUE TITLE
write a scraper to get data from github

### ISSUE THREAD

**Issue by jonorthwash** [goavki/family-visualizations#6]
We need a new scraper for this tool.  The old one got data from sourceforge's svn, where language data used to be, but it's all on github now.

The scraper should get all data used by the visualiser.  It could also potentially have a "shallow" mode where it doesn't get quite as much data (like it doesn't dig through histories to get changes in size).

**Comment by diogoscf** [comment]
One of the things the visualizer requires is knowing what "state" a language is in (prototype, development, working or production). Is there anywhere I can get this data from?

EDIT: If anybody ends up here in the future, the tables for families in the wiki have this data ([eg. for Turkic languages](http://wiki.apertium.org/wiki/Turkic_languages#Transducers))
